---
- name: Cron Setup
  hosts: all
  become: true            #cronjob -l


  tasks:
  - name: Add Cron Job 
    cron:
     name: Run Test Script
     minute: 30
     hour: 18
     day: 15
     month: "*"
     weekday: "*"
     user: azureuser
     job: /rmp/script.sh

