---
- name: Install and Start the service
  hosts: all
  become: true  
   
  vars: 
   - app: nginx
   

    
  tasks:
  - name: Installing nginx
    apt:
     name: "{{app}}"
     state: present
    tags: i-nginx 
       
  - name: starting the nginx service
    service:
      name: "{{app}}"
      state: started
      enabled: true
    tags: ss-nginx  
